groups:
- name: traefik
  rules:
  # - alert: TraefikError5XX
  #   expr: traefik_service_requests_total{code=~"5..", service="frontend@docker"}[1m] > 0
  #   for: 1m
  #   labels:
  #     severity: critical
  #   annotations:
  #     title: 'Traefik returned an error 5XX'
  #     description: 'There is a 500 error last minute on transcendence main app'
  - alert: TraefikHigh4XX
    expr: sum(rate(traefik_service_requests_total{code=~"4.."}[1m])) > 1
    for: 1m
    labels:
      severity: critical
    annotations:
      title: 'High 4xx responses by traefik'
      description: 'The rate of 4XX responses is above 1 per second for more than 1 minutes.'