global:
  scrape_interval:     5s # By default
rule_files:
  - /etc/prometheus/alerts-rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']
scrape_configs:
  - job_name: 'traefik'
    scheme: https
    metrics_path: /adm/metrics
    static_configs:
      - targets: ['proxy:443']
  - job_name: 'backend'
    scheme: https
    metrics_path: /api/metrics
    static_configs:
      - targets: ['backend:8000']
    authorization:
      type: Bearer
      credentials_file: "/etc/prometheus/token_backend"
  - job_name: 'postgres'
    scheme: https
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'cadvisor' #Sadly no native https support for cadvisor...
    metrics_path: /adm/cadvisor/metrics
    static_configs:
      - targets: ['cadvisor:8080']