"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# TODO SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
# TODO Remove fallback before submitting
SECRET_KEY_FALLBACKS = [os.environ.get('DJANGO_SECRET_KEY_FALLBACK')]

DEBUG = False

ALLOWED_HOSTS = ['backend']

# SSL
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition

# Set my custom Member model as default user class for auth
AUTH_USER_MODEL = 'game.Member'

# Set where user uploads are stored
MEDIA_ROOT = "/usr/app/backend/media"
MEDIA_URL = "https://backendimg/media/"

# Configuration of REST
REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': [
		'rest_framework_simplejwt.authentication.JWTAuthentication',
		'rest_framework.authentication.BasicAuthentication',
		'rest_framework.authentication.SessionAuthentication'
	],
	'DEFAULT_PERMISSION_CLASSES': [
		'rest_framework.permissions.IsAuthenticated'
	],
	'DEFAULT_PAGINATION_CLASS': None
}

INSTALLED_APPS = [
	'rest_framework',
	'corsheaders',
	'game',
	'django_otp',
	'django_otp.plugins.otp_totp',
	'qrcode',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django_extensions'
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'corsheaders.middleware.CorsMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django_otp.middleware.OTPMiddleware',
	'game.middleware.UpdateLastActivityMiddleware'
]

# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
	"http://frontend:3000", # Next.js
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Establishing a link with Postgres
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql',
		'NAME': os.environ.get('POSTGRES_DB'),
		'USER': os.environ.get('POSTGRES_USER'),
		'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
		'HOST': 'db',
		'PORT': '5432',
		'OPTIONS': {
			'sslmode': 'require',
			'sslcert': '/ssl/backend_' + os.environ.get('PROJECT_NAME') + '.crt',
			'sslkey': '/ssl/backend_' + os.environ.get('PROJECT_NAME') + '.key',
			'sslrootcert': '/usr/local/share/ca-certificates/CA.crt'
		}
	}
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
	{
			'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
			'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
			'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
			'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'
USE_TZ = True

# No support for translation packs, only 1 language supported
USE_I18N = False
# Support for localization (change date format based on user locale for example)
USE_L10N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
