# Generated by Django 4.2.13 on 2024-05-11 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_comment='Unique display name of a member', max_length=25, unique=True, verbose_name='Username')),
                ('email', models.EmailField(db_comment='Unique valid email adress of a member', max_length=150, unique=True, verbose_name='Email address')),
                ('avatar', models.ImageField(db_comment='Avatar of a member', default='default.png', upload_to='%Y/%m/%d', verbose_name='Avatar')),
                ('join_date', models.DateField(auto_now_add=True, db_comment='Date of registration', verbose_name='Join date')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
            managers=[
                ('objects', game.models.MemberManager()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(db_comment="First player's score in a match", default=0, verbose_name="Player 1's score")),
                ('score2', models.IntegerField(db_comment="Second player's score in a match", default=0, verbose_name="Player 2's score")),
                ('start_datetime', models.DateTimeField(auto_now_add=True, db_comment='Date and time of start of the match', verbose_name='Start of match')),
                ('end_datetime', models.DateTimeField(db_comment='Date and time of end of the match', verbose_name='End of match')),
                ('player1', models.ForeignKey(db_comment='First player in a match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p1', to=settings.AUTH_USER_MODEL, verbose_name='Player 1')),
                ('player2', models.ForeignKey(db_comment='Second player in a match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p2', to=settings.AUTH_USER_MODEL, verbose_name='Player 2')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['username'], name='username_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['join_date', 'username'], name='join_date_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['player1', 'player2'], name='players_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['end_datetime'], name='date_idx'),
        ),
    ]
