# Generated by Django 4.2.13 on 2024-05-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_member_groups_member_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(db_comment='Admin status', default=False, verbose_name='Admin status'),
        ),
    ]
