# Generated by Django 4.2.13 on 2024-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_member_is_admin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['-join_date', 'username'], name='join_date_rev_idx'),
        ),
    ]
