# Generated by Django 4.2.13 on 2024-05-17 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_member_join_date_rev_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='players_idx',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score2',
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(db_comment='Loser of the match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_lost', to=settings.AUTH_USER_MODEL, verbose_name='Loser'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_score',
            field=models.IntegerField(db_comment="Loser's score in the match", default=0, verbose_name="Loser's score"),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(db_comment='Winner of the match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to=settings.AUTH_USER_MODEL, verbose_name='Winner'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_score',
            field=models.IntegerField(db_comment="Winner's score in the match", default=0, verbose_name="Winner's score"),
        ),
        migrations.AlterField(
            model_name='match',
            name='end_datetime',
            field=models.DateTimeField(db_comment='Date and time of the end of the match', verbose_name='End of match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True, db_comment='Date and time of the start of the match', verbose_name='Start of match'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['winner'], name='winner_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['loser'], name='loser_idx'),
        ),
    ]
