# Generated by Django 4.2.13 on 2024-05-23 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_match_players_idx_remove_match_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='friends',
            field=models.ManyToManyField(blank=True, db_comment='Friends list', to=settings.AUTH_USER_MODEL, verbose_name='Friends list'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.ForeignKey(db_comment='Recipient', on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='Friend request recipient')),
                ('sender', models.ForeignKey(db_comment='Sender', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Friend request sender')),
            ],
        ),
    ]
