# Generated by Django 4.2.13 on 2024-05-23 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_member_friends_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Friends list'),
        ),
    ]
