# Generated by Django 4.2.13 on 2024-05-23 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_member_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'friend request', 'verbose_name_plural': 'friend requests'},
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='match_winner_idx',
            old_name='winner_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='match_loser_idx',
            old_name='loser_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='match_date_idx',
            old_name='date_idx',
        ),
        migrations.RenameIndex(
            model_name='member',
            new_name='member_username_idx',
            old_name='username_idx',
        ),
        migrations.RenameIndex(
            model_name='member',
            new_name='member_join_date_idx',
            old_name='join_date_idx',
        ),
        migrations.RenameIndex(
            model_name='member',
            new_name='member_join_date_rev_idx',
            old_name='join_date_rev_idx',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, db_comment='Date and time of the creation of the friend request', default=django.utils.timezone.now, verbose_name='Date and time of friend request'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['datetime'], name='friend_request_date_idx'),
        ),
    ]
