# Generated by Django 4.2.13 on 2024-06-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_friendrequest_friend_request_sender_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Activity'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_activity'], name='member_last_activity_idx'),
        ),
    ]
