# Generated by Django 4.2.13 on 2024-06-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_match3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'pong2 match', 'verbose_name_plural': 'pong2 matches'},
        ),
        migrations.AlterModelOptions(
            name='match3',
            options={'verbose_name': 'pong3 match', 'verbose_name_plural': 'pong3 matches'},
        ),
    ]
