# Generated by Django 4.2.13 on 2024-06-19 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_member_member_elo_pong_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_comment='Type of the game', default='royal', verbose_name='Game Type')),
                ('start_datetime', models.DateTimeField(auto_now_add=True, db_comment='Date and time of the start of the match', verbose_name='Start of match')),
                ('end_datetime', models.DateTimeField(db_comment='Date and time of the end of the match', verbose_name='End of match')),
            ],
            options={
                'verbose_name': 'royal match',
                'verbose_name_plural': 'royal matches',
            },
        ),
        migrations.CreateModel(
            name='RoyalPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(db_comment="Position in associated game's results", default=0, verbose_name='Position in game')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.matchr')),
                ('member', models.ForeignKey(db_comment='Player object for Royal', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='matchr',
            index=models.Index(fields=['end_datetime'], name='royal_match_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='royalplayer',
            unique_together={('match', 'position')},
        ),
    ]
