# Generated by Django 4.2.13 on 2024-06-19 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_matchr_royalplayer_matchr_royal_match_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royalplayer',
            name='position',
            field=models.PositiveSmallIntegerField(db_comment="Position in associated game's results", default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Position in game'),
        ),
    ]
