# Generated by Django 4.2.13 on 2024-06-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_royalplayer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='royalplayer',
            unique_together={('match', 'member')},
        ),
    ]
