# Generated by Django 4.2.13 on 2024-06-19 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_royalplayer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royalplayer',
            name='member',
            field=models.ForeignKey(db_comment='Player object for Royal', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
    ]
