# Generated by Django 4.2.13 on 2024-06-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_royalplayer_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='royalplayer',
            options={'ordering': ['position'], 'verbose_name': 'royal player', 'verbose_name_plural': 'royal players'},
        ),
        migrations.AddIndex(
            model_name='royalplayer',
            index=models.Index(fields=['match'], name='royal_player_match_idx'),
        ),
        migrations.AddIndex(
            model_name='royalplayer',
            index=models.Index(fields=['member'], name='royal_player_member_idx'),
        ),
    ]
