# Generated by Django 4.2.13 on 2024-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_royalplayer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='elo_royal',
            field=models.IntegerField(db_comment='ELO rating for the royal game', default=1000, verbose_name='Royal ELO rating'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['elo_royal'], name='member_elo_royal_idx'),
        ),
    ]
