# Generated by Django 4.2.13 on 2024-06-20 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_member_elo_royal_member_member_elo_royal_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchr',
            name='player_count',
            field=models.PositiveSmallIntegerField(db_comment='Number of players in the game', default=0, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)], verbose_name='Number of players'),
        ),
    ]
