# Generated by Django 4.2.13 on 2024-06-20 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_matchr_player_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchr',
            name='player_count',
            field=models.PositiveSmallIntegerField(db_comment='Number of players in the game', default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)], verbose_name='Number of players'),
        ),
        migrations.AddIndex(
            model_name='matchr',
            index=models.Index(fields=['player_count'], name='royal_match_player_count_idx'),
        ),
    ]
