# Generated by Django 4.2.13 on 2024-06-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_alter_matchr_player_count_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchr',
            name='royal_match_player_count_idx',
        ),
        migrations.RemoveField(
            model_name='matchr',
            name='player_count',
        ),
    ]
