# Generated by Django 4.2.13 on 2024-06-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_remove_matchr_royal_match_player_count_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qr_2fa',
            field=models.CharField(blank=True, db_comment='Filepath of 2FA QR code of a member', max_length=255, verbose_name='2FA QR filepath'),
        ),
    ]
