# Generated by Django 4.2.13 on 2024-06-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_member_qr_2fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='qr_2fa',
            field=models.CharField(db_comment='Filepath of 2FA QR code of a member', max_length=255, null=True, verbose_name='2FA QR filepath'),
        ),
    ]
