# Generated by Django 4.2.14 on 2024-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_alter_member_qr_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_ingame',
            field=models.BooleanField(db_comment='In-Game status', default=False, verbose_name='In-Game status'),
        ),
    ]
