# Generated by Django 4.2.15 on 2024-08-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_member_is_ingame'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='royalplayer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='royalplayer',
            name='match',
        ),
        migrations.RemoveField(
            model_name='royalplayer',
            name='member',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='member_elo_royal_idx',
        ),
        migrations.RemoveField(
            model_name='member',
            name='elo_royal',
        ),
        migrations.DeleteModel(
            name='MatchR',
        ),
        migrations.DeleteModel(
            name='RoyalPlayer',
        ),
    ]
