{
 "title": "Traefik",
 "description": "Traefik dashboard (data from prometheus) (based on Traefik by Thomas Cheronneau https://grafana.com/grafana/dashboards/4475)",
 "tags": [
  "prometheus",
  "traefik"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "service", "query": "label_values(service)" },
   { "name": "entrypoint", "query": "label_values(entrypoint)" }
  ]
 },
 "panels": [
  {
   "title": "Global stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average response time by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{}) by (service) / sum(traefik_service_request_duration_seconds_count{}) by (service)",
     "legendFormat": " {{service}}"
    }
   ]
  },
  {
   "title": "$service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "$service response time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{service=\"$service\"}) / sum(traefik_service_requests_total{service=\"$service\"}) * 1000"
    }
   ]
  },
  {
   "title": "Total requests $service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"$service\"}[$__interval]))",
     "legendFormat": "Total requests $service"
    }
   ]
  },
  {
   "title": "Status code 200 for $service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(traefik_service_requests_total{service=\"$service\",code=\"200\"}[$__interval])",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Others status code for $service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(traefik_service_requests_total{code!=\"200\", service=\"$service\"}[$__interval])",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  }
 ]
}