{
 "title": "Transcendence",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "back_total_users", "legendFormat": "Total Users" }
   ]
  },
  {
   "title": "User with 2FA",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "back_total_2fa_users", "legendFormat": "Total Users" }
   ]
  },
  {
   "title": "Online Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "back_online_users", "legendFormat": "Online Users" }
   ]
  },
  { "title": "Games", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Game played per games",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(back_total_pong2_matches)", "legendFormat": "Pong 1vs1" },
    {
     "expr": "max by() (back_total_pong3_matches)",
     "legendFormat": "Pong 2vs1"
    },
    { "expr": "max(back_total_pong3_matches)", "legendFormat": "Royal" }
   ]
  },
  {
   "title": "PONG 1vs1 - Game won per user",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "back_won_pong2_matches{player!=\"\"}",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "PONG 1vs1 - Game won per user - Time graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "back_won_pong2_matches{player!=\"\"}",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Pong 2vs1 - Paddle vs Ball",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(role) (back_won_pong3_matches{role!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PONG 2vs1 - Game won per user",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(player) (back_won_pong3_matches{player!=\"\"})",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "PONG 2vs1 - Game won per user - Time Graph",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(player) (back_won_pong3_matches{player!=\"\"})",
     "legendFormat": "{{player}}"
    }
   ]
  },
  { "title": "Elo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Elo PONG",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "back_users_elo_pong{user!=\"\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  { "title": "Friendships", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Friend request received per user",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "back_total_friend_requests{role=\"recipient\"}",
     "legendFormat": "{{user}}({{role}})"
    }
   ]
  },
  {
   "title": "Friend request send per user",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "back_total_friend_requests{role=\"sender\"}",
     "legendFormat": "{{user}}({{role}})"
    }
   ]
  }
 ]
}